---
- name: Pull Docker Image of Frontend
  hosts: localhost
  vars:
    ansible_python_interpreter: /usr/bin/python3.10
  tasks:
    - name: Pull image
      shell: docker pull sashank369/front:latest
    - name: Start docker service
      service:
        name: docker
        state: started
    - name: Running container
      shell: docker run -it -d --name Frontend sashank369/front